//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbbookEntities : DbContext
    {
        public dbbookEntities()
            : base("name=dbbookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_account> tbl_account { get; set; }
        public DbSet<tbl_author> tbl_author { get; set; }
        public DbSet<tbl_avtofbook> tbl_avtofbook { get; set; }
        public DbSet<tbl_avtofcus> tbl_avtofcus { get; set; }
        public DbSet<tbl_book> tbl_book { get; set; }
        public DbSet<tbl_cart> tbl_cart { get; set; }
        public DbSet<tbl_category> tbl_category { get; set; }
        public DbSet<tbl_customer> tbl_customer { get; set; }
        public DbSet<tbl_order> tbl_order { get; set; }
        public DbSet<tbl_publisher> tbl_publisher { get; set; }
        public DbSet<tbl_role> tbl_role { get; set; }
        public DbSet<tbl_status> tbl_status { get; set; }
    }
}
