//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        public tbl_customer()
        {
            this.tbl_cart = new HashSet<tbl_cart>();
            this.tbl_order = new HashSet<tbl_order>();
        }
    
        public int cus_id { get; set; }
        public string cus_name { get; set; }
        public string cus_phone { get; set; }
        public string cus_address { get; set; }
        public Nullable<int> cus_acc_fk { get; set; }
    
        public virtual tbl_account tbl_account { get; set; }
        public virtual tbl_avtofcus tbl_avtofcus { get; set; }
        public virtual ICollection<tbl_cart> tbl_cart { get; set; }
        public virtual ICollection<tbl_order> tbl_order { get; set; }
    }
}
