//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_role
    {
        public tbl_role()
        {
            this.tbl_account = new HashSet<tbl_account>();
        }
    
        public int role_id { get; set; }
        public string role_name { get; set; }
        public string role_description { get; set; }
    
        public virtual ICollection<tbl_account> tbl_account { get; set; }
    }
}
