//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_account
    {
        public tbl_account()
        {
            this.tbl_customer = new HashSet<tbl_customer>();
        }
    
        public int acc_id { get; set; }
        public string acc_username { get; set; }
        public string acc_password { get; set; }
        public Nullable<int> acc_role_fk { get; set; }
    
        public virtual tbl_role tbl_role { get; set; }
        public virtual ICollection<tbl_customer> tbl_customer { get; set; }
    }
}
