//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_avtofcus
    {
        public int avtofcus_id { get; set; }
        public byte[] avtofcus_img { get; set; }
    
        public virtual tbl_customer tbl_customer { get; set; }
    }
}
