//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSellingWebsite_BeerBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_
    {
        public int AccID_ { get; set; }
        public string Username_ { get; set; }
        public string Email_ { get; set; }
        public string Password_ { get; set; }
        public Nullable<System.DateTime> DateCreated_ { get; set; }
        public Nullable<bool> Status_ { get; set; }
        public int CustomerID_ { get; set; }
        public int AuID_ { get; set; }
    
        public virtual Authorization_ Authorization_ { get; set; }
        public virtual Customer_ Customer_ { get; set; }
    }
}
