//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSellingWebsite_BeerBook.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BEERBOOKEntities : DbContext
    {
        public BEERBOOKEntities()
            : base("name=BEERBOOKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account_> Account_ { get; set; }
        public virtual DbSet<Author_> Author_ { get; set; }
        public virtual DbSet<Authorization_> Authorization_ { get; set; }
        public virtual DbSet<Book_> Book_ { get; set; }
        public virtual DbSet<BookHouse_> BookHouse_ { get; set; }
        public virtual DbSet<Customer_> Customer_ { get; set; }
        public virtual DbSet<PayMethod_> PayMethod_ { get; set; }
        public virtual DbSet<PurchaseOrderDetails_> PurchaseOrderDetails_ { get; set; }
        public virtual DbSet<PurchaseOrders_> PurchaseOrders_ { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
