//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSellingWebsite_BeerBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_()
        {
            this.PurchaseOrderDetails_ = new HashSet<PurchaseOrderDetails_>();
        }
    
        public int BookID_ { get; set; }
        public string Name_ { get; set; }
        public long Quantity_ { get; set; }
        public long Price_ { get; set; }
        public string Description_ { get; set; }
        public int AuthorID_ { get; set; }
        public int BhID_ { get; set; }
        public string Language_ { get; set; }
        public string Image_ { get; set; }
    
        public virtual Author_ Author_ { get; set; }
        public virtual BookHouse_ BookHouse_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetails_> PurchaseOrderDetails_ { get; set; }
    }
}
