//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSellingWebsite_BeerBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_()
        {
            this.Account_ = new HashSet<Account_>();
            this.PurchaseOrderDetails_ = new HashSet<PurchaseOrderDetails_>();
        }
    
        public int CustomerID_ { get; set; }
        public string Name_ { get; set; }
        public Nullable<System.DateTime> BirthDate_ { get; set; }
        public Nullable<bool> Sex_ { get; set; }
        public string Email_ { get; set; }
        public string Phone_ { get; set; }
        public string Address_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_> Account_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetails_> PurchaseOrderDetails_ { get; set; }
    }
}
