//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSellingWebsite_BeerBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayMethod_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PayMethod_()
        {
            this.PurchaseOrders_ = new HashSet<PurchaseOrders_>();
        }
    
        public int PayID_ { get; set; }
        public string Name_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrders_> PurchaseOrders_ { get; set; }
    }
}
