//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSellingWebsite_BeerBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrders_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrders_()
        {
            this.PurchaseOrderDetails_ = new HashSet<PurchaseOrderDetails_>();
        }
    
        public int PoID_ { get; set; }
        public Nullable<System.DateTime> OrderDate_ { get; set; }
        public Nullable<System.DateTime> DeliveryDate_ { get; set; }
        public Nullable<bool> Status_ { get; set; }
        public int PayID_ { get; set; }
    
        public virtual PayMethod_ PayMethod_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetails_> PurchaseOrderDetails_ { get; set; }
    }
}
