//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSellingWebsite_BeerBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetails_
    {
        public int CustomerID_ { get; set; }
        public int PoID_ { get; set; }
        public int BookID_ { get; set; }
        public int Quantity { get; set; }
        public long Cost { get; set; }
    
        public virtual Book_ Book_ { get; set; }
        public virtual Customer_ Customer_ { get; set; }
        public virtual PurchaseOrders_ PurchaseOrders_ { get; set; }
    }
}
